[2024-09-04T21:24:26.090+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-04T21:24:24.617669+00:00 [queued]>
[2024-09-04T21:24:26.093+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-04T21:24:24.617669+00:00 [queued]>
[2024-09-04T21:24:26.094+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-04T21:24:26.099+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_daily_order_update_task> on 2024-09-04 21:24:24.617669+00:00
[2024-09-04T21:24:26.101+0000] {standard_task_runner.py:57} INFO - Started process 216 to run task
[2024-09-04T21:24:26.104+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'run_daily_order_update_task', 'manual__2024-09-04T21:24:24.617669+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmp7ikvbla4']
[2024-09-04T21:24:26.106+0000] {standard_task_runner.py:85} INFO - Job 163: Subtask run_daily_order_update_task
[2024-09-04T21:24:26.138+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-04T21:24:24.617669+00:00 [running]> on host bb180eb43ad3
[2024-09-04T21:24:26.177+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='run_daily_order_update_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-04T21:24:24.617669+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-04T21:24:24.617669+00:00'
[2024-09-04T21:24:26.178+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-04T21:24:26.178+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec python-scripts-container python3 /opt/python_scripts/run_daily_orders_update.py']
[2024-09-04T21:24:26.182+0000] {subprocess.py:86} INFO - Output:
[2024-09-04T21:24:26.218+0000] {subprocess.py:93} INFO - Error response from daemon: container bdfadd229c22ae3af101e35ff87b0556fd9c524ec7744ab46f685d22171f2351 is not running
[2024-09-04T21:24:26.220+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-04T21:24:26.228+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-04T21:24:26.230+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=run_daily_order_update_task, execution_date=20240904T212424, start_date=20240904T212426, end_date=20240904T212426
[2024-09-04T21:24:26.236+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 163 for task run_daily_order_update_task (Bash command failed. The command returned a non-zero exit code 1.; 216)
[2024-09-04T21:24:26.244+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-04T21:24:26.252+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
