[2024-09-05T07:05:07.936+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-05T07:05:06.155200+00:00 [queued]>
[2024-09-05T07:05:07.941+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-05T07:05:06.155200+00:00 [queued]>
[2024-09-05T07:05:07.941+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-05T07:05:07.948+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_daily_order_update_task> on 2024-09-05 07:05:06.155200+00:00
[2024-09-05T07:05:07.954+0000] {standard_task_runner.py:57} INFO - Started process 501 to run task
[2024-09-05T07:05:07.958+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'run_daily_order_update_task', 'manual__2024-09-05T07:05:06.155200+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmped252_l7']
[2024-09-05T07:05:07.963+0000] {standard_task_runner.py:85} INFO - Job 171: Subtask run_daily_order_update_task
[2024-09-05T07:05:08.092+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-05T07:05:06.155200+00:00 [running]> on host c463b27df1b4
[2024-09-05T07:05:08.164+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='run_daily_order_update_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-05T07:05:06.155200+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-05T07:05:06.155200+00:00'
[2024-09-05T07:05:08.166+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-05T07:05:08.167+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec python-scripts-container python3 /opt/python_scripts/run_daily_orders_update.py']
[2024-09-05T07:05:08.171+0000] {subprocess.py:86} INFO - Output:
[2024-09-05T07:05:08.258+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-09-05T07:05:08.259+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-05T07:05:08.267+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-05T07:05:08.271+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=run_daily_order_update_task, execution_date=20240905T070506, start_date=20240905T070507, end_date=20240905T070508
[2024-09-05T07:05:08.278+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 171 for task run_daily_order_update_task (Bash command failed. The command returned a non-zero exit code 1.; 501)
[2024-09-05T07:05:08.309+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-05T07:05:08.319+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
