[2024-09-05T06:16:54.214+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task scheduled__2024-09-05T04:00:00+00:00 [queued]>
[2024-09-05T06:16:54.217+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task scheduled__2024-09-05T04:00:00+00:00 [queued]>
[2024-09-05T06:16:54.217+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-05T06:16:54.222+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_daily_order_update_task> on 2024-09-05 04:00:00+00:00
[2024-09-05T06:16:54.225+0000] {standard_task_runner.py:57} INFO - Started process 208 to run task
[2024-09-05T06:16:54.227+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'run_daily_order_update_task', 'scheduled__2024-09-05T04:00:00+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmpxc81lbuq']
[2024-09-05T06:16:54.228+0000] {standard_task_runner.py:85} INFO - Job 167: Subtask run_daily_order_update_task
[2024-09-05T06:16:54.251+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.run_daily_order_update_task scheduled__2024-09-05T04:00:00+00:00 [running]> on host c463b27df1b4
[2024-09-05T06:16:54.288+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='run_daily_order_update_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-05T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-05T04:00:00+00:00'
[2024-09-05T06:16:54.289+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-05T06:16:54.289+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec python-scripts-container python3 /opt/python_scripts/run_daily_orders_update.py']
[2024-09-05T06:16:54.294+0000] {subprocess.py:86} INFO - Output:
[2024-09-05T06:16:54.391+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-09-05T06:16:54.392+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-05T06:16:54.407+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-05T06:16:54.412+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=run_daily_order_update_task, execution_date=20240905T040000, start_date=20240905T061654, end_date=20240905T061654
[2024-09-05T06:16:54.433+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 167 for task run_daily_order_update_task (Bash command failed. The command returned a non-zero exit code 1.; 208)
[2024-09-05T06:16:54.448+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-05T06:16:54.483+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
