[2024-09-05T11:33:28.824+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-05T11:33:27.520475+00:00 [queued]>
[2024-09-05T11:33:28.827+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-05T11:33:27.520475+00:00 [queued]>
[2024-09-05T11:33:28.827+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-05T11:33:28.833+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_daily_order_update_task> on 2024-09-05 11:33:27.520475+00:00
[2024-09-05T11:33:28.836+0000] {standard_task_runner.py:57} INFO - Started process 254 to run task
[2024-09-05T11:33:28.839+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'run_daily_order_update_task', 'manual__2024-09-05T11:33:27.520475+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmpke37wdr_']
[2024-09-05T11:33:28.843+0000] {standard_task_runner.py:85} INFO - Job 221: Subtask run_daily_order_update_task
[2024-09-05T11:33:28.869+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-05T11:33:27.520475+00:00 [running]> on host 2c451b520589
[2024-09-05T11:33:28.925+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='run_daily_order_update_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-05T11:33:27.520475+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-05T11:33:27.520475+00:00'
[2024-09-05T11:33:28.927+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-05T11:33:28.927+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec python-scripts-container python3 /opt/python_scripts/run_daily_orders_update.py']
[2024-09-05T11:33:28.932+0000] {subprocess.py:86} INFO - Output:
[2024-09-05T11:33:30.809+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-05T11:33:30.812+0000] {subprocess.py:93} INFO -   File "/opt/python_scripts/run_daily_orders_update.py", line 26, in <module>
[2024-09-05T11:33:30.812+0000] {subprocess.py:93} INFO - fetching data from 2024-09-05 10:28:50 and 2024-09-05 11:03:29
[2024-09-05T11:33:30.813+0000] {subprocess.py:93} INFO -     orders = LongPeriodOrdersFetcher(LastUpdatedAfter, LastUpdatedBefore).GetOrdersInLongPeriod()
[2024-09-05T11:33:30.813+0000] {subprocess.py:93} INFO -   File "/opt/python_scripts/utils/amz_orders_fetcher.py", line 84, in GetOrdersInLongPeriod
[2024-09-05T11:33:30.814+0000] {subprocess.py:93} INFO -     orders, status_code = self.GetOrders()
[2024-09-05T11:33:30.814+0000] {subprocess.py:93} INFO -   File "/opt/python_scripts/utils/amz_orders_fetcher.py", line 35, in GetOrders
[2024-09-05T11:33:30.814+0000] {subprocess.py:93} INFO -     print(orders[1])
[2024-09-05T11:33:30.815+0000] {subprocess.py:93} INFO - IndexError: list index out of range
[2024-09-05T11:33:30.843+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-05T11:33:30.859+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-05T11:33:30.863+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=run_daily_order_update_task, execution_date=20240905T113327, start_date=20240905T113328, end_date=20240905T113330
[2024-09-05T11:33:30.877+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 221 for task run_daily_order_update_task (Bash command failed. The command returned a non-zero exit code 1.; 254)
[2024-09-05T11:33:30.891+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-05T11:33:30.907+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
