[2024-09-11T08:49:15.072+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.dbt_run scheduled__2024-09-11T06:00:00+00:00 [queued]>
[2024-09-11T08:49:15.077+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.dbt_run scheduled__2024-09-11T06:00:00+00:00 [queued]>
[2024-09-11T08:49:15.077+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-11T08:49:15.085+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2024-09-11 06:00:00+00:00
[2024-09-11T08:49:15.087+0000] {standard_task_runner.py:57} INFO - Started process 234 to run task
[2024-09-11T08:49:15.090+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'dbt_run', 'scheduled__2024-09-11T06:00:00+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmpfh12841j']
[2024-09-11T08:49:15.093+0000] {standard_task_runner.py:85} INFO - Job 335: Subtask dbt_run
[2024-09-11T08:49:15.119+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.dbt_run scheduled__2024-09-11T06:00:00+00:00 [running]> on host 2c451b520589
[2024-09-11T08:49:15.158+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T06:00:00+00:00'
[2024-09-11T08:49:15.159+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-11T08:49:15.159+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec dbt_container dbt run --project-dir /opt/dbt_vne/dbt_vne/']
[2024-09-11T08:49:15.164+0000] {subprocess.py:86} INFO - Output:
[2024-09-11T08:49:16.148+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2024-09-11T08:49:16.149+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2024-09-11T08:49:16.149+0000] {subprocess.py:93} INFO - 
[2024-09-11T08:49:16.149+0000] {subprocess.py:93} INFO - Error: Invalid value for '--project-dir': Path '/opt/dbt_vne/dbt_vne/' does not exist.
[2024-09-11T08:49:16.264+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-11T08:49:16.277+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-11T08:49:16.281+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=dbt_run, execution_date=20240911T060000, start_date=20240911T084915, end_date=20240911T084916
[2024-09-11T08:49:16.291+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 335 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 234)
[2024-09-11T08:49:16.314+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-11T08:49:16.327+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
