[2024-09-09T12:00:01.375+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task scheduled__2024-09-09T10:00:00+00:00 [queued]>
[2024-09-09T12:00:01.379+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task scheduled__2024-09-09T10:00:00+00:00 [queued]>
[2024-09-09T12:00:01.379+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-09T12:00:01.385+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_daily_order_update_task> on 2024-09-09 10:00:00+00:00
[2024-09-09T12:00:01.388+0000] {standard_task_runner.py:57} INFO - Started process 836 to run task
[2024-09-09T12:00:01.390+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'run_daily_order_update_task', 'scheduled__2024-09-09T10:00:00+00:00', '--job-id', '240', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmpi59es1mm']
[2024-09-09T12:00:01.393+0000] {standard_task_runner.py:85} INFO - Job 240: Subtask run_daily_order_update_task
[2024-09-09T12:00:01.417+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.run_daily_order_update_task scheduled__2024-09-09T10:00:00+00:00 [running]> on host 5c121da44a2d
[2024-09-09T12:00:01.473+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='run_daily_order_update_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T10:00:00+00:00'
[2024-09-09T12:00:01.474+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-09T12:00:01.475+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec python-scripts-container python3 /opt/python_scripts/run_fetch_raw_amazon_Orders.py']
[2024-09-09T12:00:01.483+0000] {subprocess.py:86} INFO - Output:
[2024-09-09T12:00:03.161+0000] {subprocess.py:93} INFO - fetching data from 2024-09-09 10:06:14 and 2024-09-09 11:30:02
[2024-09-09T12:00:03.163+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-09T12:00:03.164+0000] {subprocess.py:93} INFO -   File "/opt/python_scripts/run_fetch_raw_amazon_Orders.py", line 26, in <module>
[2024-09-09T12:00:03.164+0000] {subprocess.py:93} INFO -     orders = LongPeriodOrdersFetcher(LastUpdatedAfter, LastUpdatedBefore).GetOrdersInLongPeriod()
[2024-09-09T12:00:03.165+0000] {subprocess.py:93} INFO -   File "/opt/python_scripts/utils/amz_orders_fetcher.py", line 84, in GetOrdersInLongPeriod
[2024-09-09T12:00:03.165+0000] {subprocess.py:93} INFO -     orders, status_code = self.GetOrders()
[2024-09-09T12:00:03.165+0000] {subprocess.py:93} INFO -   File "/opt/python_scripts/utils/amz_orders_fetcher.py", line 35, in GetOrders
[2024-09-09T12:00:03.166+0000] {subprocess.py:93} INFO -     print(orders[1])
[2024-09-09T12:00:03.166+0000] {subprocess.py:93} INFO - IndexError: list index out of range
[2024-09-09T12:00:03.195+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-09T12:00:03.213+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-09T12:00:03.218+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=run_daily_order_update_task, execution_date=20240909T100000, start_date=20240909T120001, end_date=20240909T120003
[2024-09-09T12:00:03.230+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 240 for task run_daily_order_update_task (Bash command failed. The command returned a non-zero exit code 1.; 836)
[2024-09-09T12:00:03.270+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-09T12:00:03.287+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
