[2024-09-04T21:12:07.234+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-04T21:12:05.896515+00:00 [queued]>
[2024-09-04T21:12:07.238+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-04T21:12:05.896515+00:00 [queued]>
[2024-09-04T21:12:07.238+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-04T21:12:07.243+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_daily_order_update_task> on 2024-09-04 21:12:05.896515+00:00
[2024-09-04T21:12:07.245+0000] {standard_task_runner.py:57} INFO - Started process 201 to run task
[2024-09-04T21:12:07.247+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'run_daily_order_update_task', 'manual__2024-09-04T21:12:05.896515+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmp8wptutet']
[2024-09-04T21:12:07.249+0000] {standard_task_runner.py:85} INFO - Job 159: Subtask run_daily_order_update_task
[2024-09-04T21:12:07.273+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-04T21:12:05.896515+00:00 [running]> on host d055a2d35f28
[2024-09-04T21:12:07.323+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='run_daily_order_update_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-04T21:12:05.896515+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-04T21:12:05.896515+00:00'
[2024-09-04T21:12:07.324+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-04T21:12:07.324+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec python-scripts-container python3 /opt/python_scripts/run_daily_orders_update.py']
[2024-09-04T21:12:07.330+0000] {subprocess.py:86} INFO - Output:
[2024-09-04T21:12:07.362+0000] {subprocess.py:93} INFO - Error response from daemon: container b82d010619a3838b51c07dd748d29b2a21970cd626beb14c1ccd312f83292a25 is not running
[2024-09-04T21:12:07.363+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-04T21:12:07.368+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-04T21:12:07.370+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=run_daily_order_update_task, execution_date=20240904T211205, start_date=20240904T211207, end_date=20240904T211207
[2024-09-04T21:12:07.375+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 159 for task run_daily_order_update_task (Bash command failed. The command returned a non-zero exit code 1.; 201)
[2024-09-04T21:12:07.386+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-04T21:12:07.401+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
