[2024-09-09T04:47:04.231+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-09T04:47:03.127545+00:00 [queued]>
[2024-09-09T04:47:04.234+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-09T04:47:03.127545+00:00 [queued]>
[2024-09-09T04:47:04.234+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-09T04:47:04.240+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_daily_order_update_task> on 2024-09-09 04:47:03.127545+00:00
[2024-09-09T04:47:04.243+0000] {standard_task_runner.py:57} INFO - Started process 229 to run task
[2024-09-09T04:47:04.251+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'run_daily_order_update_task', 'manual__2024-09-09T04:47:03.127545+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmpbjl5fzuz']
[2024-09-09T04:47:04.260+0000] {standard_task_runner.py:85} INFO - Job 226: Subtask run_daily_order_update_task
[2024-09-09T04:47:04.295+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.run_daily_order_update_task manual__2024-09-09T04:47:03.127545+00:00 [running]> on host 2c451b520589
[2024-09-09T04:47:04.335+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='run_daily_order_update_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T04:47:03.127545+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T04:47:03.127545+00:00'
[2024-09-09T04:47:04.336+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-09T04:47:04.336+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec python-scripts-container python3 /opt/python_scripts/run_fetch_raw_amazon_Orders.py']
[2024-09-09T04:47:04.341+0000] {subprocess.py:86} INFO - Output:
[2024-09-09T04:47:04.475+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/python_scripts/run_fetch_raw_amazon_Orders.py': [Errno 2] No such file or directory
[2024-09-09T04:47:04.479+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-09T04:47:04.486+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-09T04:47:04.488+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=run_daily_order_update_task, execution_date=20240909T044703, start_date=20240909T044704, end_date=20240909T044704
[2024-09-09T04:47:04.494+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 226 for task run_daily_order_update_task (Bash command failed. The command returned a non-zero exit code 2.; 229)
[2024-09-09T04:47:04.514+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-09T04:47:04.527+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
