[2024-09-03T20:00:00.809+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task scheduled__2024-09-03T18:00:00+00:00 [queued]>
[2024-09-03T20:00:00.813+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task scheduled__2024-09-03T18:00:00+00:00 [queued]>
[2024-09-03T20:00:00.813+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-03T20:00:00.818+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_daily_order_update_task> on 2024-09-03 18:00:00+00:00
[2024-09-03T20:00:00.821+0000] {standard_task_runner.py:57} INFO - Started process 981 to run task
[2024-09-03T20:00:00.823+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'run_daily_order_update_task', 'scheduled__2024-09-03T18:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmpaoj7hmxe']
[2024-09-03T20:00:00.824+0000] {standard_task_runner.py:85} INFO - Job 148: Subtask run_daily_order_update_task
[2024-09-03T20:00:00.862+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.run_daily_order_update_task scheduled__2024-09-03T18:00:00+00:00 [running]> on host 029975ab4b18
[2024-09-03T20:00:00.899+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='run_daily_order_update_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-03T18:00:00+00:00'
[2024-09-03T20:00:00.900+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-03T20:00:00.901+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/python_scripts/run_daily_orders_update.py']
[2024-09-03T20:00:00.905+0000] {subprocess.py:86} INFO - Output:
[2024-09-03T20:00:02.334+0000] {subprocess.py:93} INFO - fetching data from 2024-09-03 19:10:58 and 2024-09-03 19:30:01
[2024-09-03T20:00:02.337+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-09-03T20:00:02.340+0000] {subprocess.py:93} INFO -   File "/opt/***/python_scripts/run_daily_orders_update.py", line 26, in <module>
[2024-09-03T20:00:02.344+0000] {subprocess.py:93} INFO -     orders = LongPeriodOrdersFetcher(LastUpdatedAfter, LastUpdatedBefore).GetOrdersInLongPeriod()
[2024-09-03T20:00:02.345+0000] {subprocess.py:93} INFO -   File "/opt/***/python_scripts/utils/amz_orders_fetcher.py", line 84, in GetOrdersInLongPeriod
[2024-09-03T20:00:02.345+0000] {subprocess.py:93} INFO -     orders, status_code = self.GetOrders()
[2024-09-03T20:00:02.345+0000] {subprocess.py:93} INFO -   File "/opt/***/python_scripts/utils/amz_orders_fetcher.py", line 35, in GetOrders
[2024-09-03T20:00:02.345+0000] {subprocess.py:93} INFO -     print(orders[1])
[2024-09-03T20:00:02.346+0000] {subprocess.py:93} INFO - IndexError: list index out of range
[2024-09-03T20:00:02.364+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-03T20:00:02.378+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-03T20:00:02.381+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=run_daily_order_update_task, execution_date=20240903T180000, start_date=20240903T200000, end_date=20240903T200002
[2024-09-03T20:00:02.396+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 148 for task run_daily_order_update_task (Bash command failed. The command returned a non-zero exit code 1.; 981)
[2024-09-03T20:00:02.431+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-03T20:00:02.447+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
