[2024-09-11T08:54:28.892+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.dbt_run manual__2024-09-11T08:54:05.736558+00:00 [queued]>
[2024-09-11T08:54:28.896+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.dbt_run manual__2024-09-11T08:54:05.736558+00:00 [queued]>
[2024-09-11T08:54:28.896+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-11T08:54:28.901+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2024-09-11 08:54:05.736558+00:00
[2024-09-11T08:54:28.905+0000] {standard_task_runner.py:57} INFO - Started process 204 to run task
[2024-09-11T08:54:28.907+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'dbt_run', 'manual__2024-09-11T08:54:05.736558+00:00', '--job-id', '341', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmpewwdkb71']
[2024-09-11T08:54:28.909+0000] {standard_task_runner.py:85} INFO - Job 341: Subtask dbt_run
[2024-09-11T08:54:28.932+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.dbt_run manual__2024-09-11T08:54:05.736558+00:00 [running]> on host 5c121da44a2d
[2024-09-11T08:54:28.971+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T08:54:05.736558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-11T08:54:05.736558+00:00'
[2024-09-11T08:54:28.972+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-11T08:54:28.972+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec dbt_container dbt run --project-dir /opt/dbt_vne/dbt/dbt_vne/']
[2024-09-11T08:54:28.976+0000] {subprocess.py:86} INFO - Output:
[2024-09-11T08:54:29.863+0000] {subprocess.py:93} INFO - [0m08:54:29  Running with dbt=1.8.6
[2024-09-11T08:54:29.864+0000] {subprocess.py:93} INFO - [0m08:54:29  Encountered an error:
[2024-09-11T08:54:29.865+0000] {subprocess.py:93} INFO - Runtime Error
[2024-09-11T08:54:29.865+0000] {subprocess.py:93} INFO -   Could not find profile named 'dbt_vne'
[2024-09-11T08:54:30.602+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-11T08:54:30.616+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-11T08:54:30.619+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=dbt_run, execution_date=20240911T085405, start_date=20240911T085428, end_date=20240911T085430
[2024-09-11T08:54:30.639+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 341 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 204)
[2024-09-11T08:54:30.659+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-11T08:54:30.685+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
