[2024-09-09T21:01:13.283+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.dbt_run manual__2024-09-09T21:00:50.141854+00:00 [queued]>
[2024-09-09T21:01:13.287+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.dbt_run manual__2024-09-09T21:00:50.141854+00:00 [queued]>
[2024-09-09T21:01:13.287+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-09T21:01:13.292+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dbt_run> on 2024-09-09 21:00:50.141854+00:00
[2024-09-09T21:01:13.296+0000] {standard_task_runner.py:57} INFO - Started process 237 to run task
[2024-09-09T21:01:13.298+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'dbt_run', 'manual__2024-09-09T21:00:50.141854+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmp73gskm8g']
[2024-09-09T21:01:13.300+0000] {standard_task_runner.py:85} INFO - Job 270: Subtask dbt_run
[2024-09-09T21:01:13.324+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.dbt_run manual__2024-09-09T21:00:50.141854+00:00 [running]> on host 2c451b520589
[2024-09-09T21:01:13.376+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T21:00:50.141854+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T21:00:50.141854+00:00'
[2024-09-09T21:01:13.378+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-09T21:01:13.378+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec dbt_container dbt run']
[2024-09-09T21:01:13.383+0000] {subprocess.py:86} INFO - Output:
[2024-09-09T21:01:14.474+0000] {subprocess.py:93} INFO - [0m21:01:14  Running with dbt=1.8.6
[2024-09-09T21:01:14.476+0000] {subprocess.py:93} INFO - [0m21:01:14  Encountered an error:
[2024-09-09T21:01:14.476+0000] {subprocess.py:93} INFO - Runtime Error
[2024-09-09T21:01:14.476+0000] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /opt/dbt_vne/dbt_project.yml
[2024-09-09T21:01:14.476+0000] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2024-09-09T21:01:14.476+0000] {subprocess.py:93} INFO - 
[2024-09-09T21:01:15.179+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-09T21:01:15.210+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-09T21:01:15.215+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=dbt_run, execution_date=20240909T210050, start_date=20240909T210113, end_date=20240909T210115
[2024-09-09T21:01:15.228+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 270 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 237)
[2024-09-09T21:01:15.286+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-09T21:01:15.316+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
