[2024-09-04T20:58:55.330+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task scheduled__2024-09-04T18:00:00+00:00 [queued]>
[2024-09-04T20:58:55.337+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_daily_order_update_dag.run_daily_order_update_task scheduled__2024-09-04T18:00:00+00:00 [queued]>
[2024-09-04T20:58:55.338+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-09-04T20:58:55.349+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_daily_order_update_task> on 2024-09-04 18:00:00+00:00
[2024-09-04T20:58:55.356+0000] {standard_task_runner.py:57} INFO - Started process 204 to run task
[2024-09-04T20:58:55.358+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_daily_order_update_dag', 'run_daily_order_update_task', 'scheduled__2024-09-04T18:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/run_daily_order_update.py', '--cfg-path', '/tmp/tmpeyrt9kw3']
[2024-09-04T20:58:55.360+0000] {standard_task_runner.py:85} INFO - Job 155: Subtask run_daily_order_update_task
[2024-09-04T20:58:55.399+0000] {task_command.py:415} INFO - Running <TaskInstance: run_daily_order_update_dag.run_daily_order_update_task scheduled__2024-09-04T18:00:00+00:00 [running]> on host 194aa7c7d57f
[2024-09-04T20:58:55.444+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_daily_order_update_dag' AIRFLOW_CTX_TASK_ID='run_daily_order_update_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-04T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-04T18:00:00+00:00'
[2024-09-04T20:58:55.445+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-04T20:58:55.445+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec python-scripts-container python3 /opt/python_scripts/run_daily_orders_update.py']
[2024-09-04T20:58:55.450+0000] {subprocess.py:86} INFO - Output:
[2024-09-04T20:58:55.537+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-09-04T20:58:55.538+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-04T20:58:55.545+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-04T20:58:55.548+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=run_daily_order_update_dag, task_id=run_daily_order_update_task, execution_date=20240904T180000, start_date=20240904T205855, end_date=20240904T205855
[2024-09-04T20:58:55.557+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 155 for task run_daily_order_update_task (Bash command failed. The command returned a non-zero exit code 1.; 204)
[2024-09-04T20:58:55.578+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-09-04T20:58:55.587+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
